server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;

    index index.html;

    # Serve static files
    location /static/ {
        try_files $uri =404;
    }

    # Handle all other routes with index.html (for React Router)
    location / {
        try_files $uri /index.html;
    }
}
